export {default as Board} from './board'
export {default as Footer} from './footer'
export {default as Game} from './game'
export {default as Header} from './header'
export {default as Modal} from './modal'
export {default as Nav} from './nav'
export {default as Piece} from './piece'
export {default as SelectLine} from './select'
